language: objective-c
osx_image: xcode10.1
env:
  global:
  - FRAMEWORK_NAME=MXSegmentedControl
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
install:
- gem install cocoapods
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild -project MXSegmentedControl.xcodeproj -scheme $FRAMEWORK_NAME
  -sdk iphonesimulator12.1 -configuration Release | xcpretty -c
- pod lib lint --quick
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  api_key:
    secure: GCbSn67brClZCNGbnlqGkwnWjFLSgYwWkjAOhkqBGIKzh/pARW227QXdDZP9vPz3oLxO/ux/tM1aojweakJCzIoYXENijTcB5rt7teUDsFiH/UInjfTCxNRLNzREUrvwOywAwEq37Ysdw3QH222SnJIVPl14ucwCyXXDMMQUmeyHLJg46AfNhZBheuWdzH5skAel9K68FOMeW9rbDEAUiXi+UHFRfmpEy0g0ukfVsVmnXB7YYQLN7ATz3fTwe6rMwPBneh5eibG7mNA81ROfsyLV7JUibjSzDIaXYPjsS+PCD8c7hWgfaTUdEeqjgOAAhwlbJz0yq5Z/ONtpRoCVFzniMV9gghr32rrt8+RvyrL9ELiqoWg9IvTQg9gNZ0wtMyT0pPTRuFxX4iD4kd0Q4YQjiPRsekxN3sOInE/njBYer69m3+geX25PcAxLCSZiuj2tXEcm4GPrApX+M822uU1PFq/8yOw6z8zfdTTgKu6l0HJaDTtqQ9BLU7m5lf0B2xQ7aloRucBPoJK+G2xOC/z6uZ06vJPoHi4eNRuiCSbThWg9NCBnWcAqYfcK/0kbQTc7E2olI13Wo5hXjXLQTpWIjkRt42Y5d11Hy4tUDF6qCx696W3rWWZnkkEWqtA7n0YYxhws8MiK7X1sedx7XrF8UfZU33TybPXt7pv726s=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: maxep/MXSegmentedControl
    tags: true
